// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFttQJNFBBunDX2LuLavDfQluklAh7L0',
    appId: '1:529491180100:web:8d2e744963673160b1da11',
    messagingSenderId: '529491180100',
    projectId: 'bloggermanager-f1e21',
    authDomain: 'bloggermanager-f1e21.firebaseapp.com',
    storageBucket: 'bloggermanager-f1e21.firebasestorage.app',
    measurementId: 'G-F276Y3JF7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLASCeTb22osgFFGQbnXSGnQ5mh5DJNIY',
    appId: '1:529491180100:android:90b04296d66fc777b1da11',
    messagingSenderId: '529491180100',
    projectId: 'bloggermanager-f1e21',
    storageBucket: 'bloggermanager-f1e21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1CV8uA8qOXtsPJMZZfWmG5S1TYRDsCE',
    appId: '1:529491180100:ios:057b5710187fdd6cb1da11',
    messagingSenderId: '529491180100',
    projectId: 'bloggermanager-f1e21',
    storageBucket: 'bloggermanager-f1e21.firebasestorage.app',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb1CV8uA8qOXtsPJMZZfWmG5S1TYRDsCE',
    appId: '1:529491180100:ios:057b5710187fdd6cb1da11',
    messagingSenderId: '529491180100',
    projectId: 'bloggermanager-f1e21',
    storageBucket: 'bloggermanager-f1e21.firebasestorage.app',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFttQJNFBBunDX2LuLavDfQluklAh7L0',
    appId: '1:529491180100:web:6c8a8590e81cf448b1da11',
    messagingSenderId: '529491180100',
    projectId: 'bloggermanager-f1e21',
    authDomain: 'bloggermanager-f1e21.firebaseapp.com',
    storageBucket: 'bloggermanager-f1e21.firebasestorage.app',
    measurementId: 'G-2RYNDWP2D9',
  );
}
